Question 1


In [4]:
#to combine two lists
A = [1,2,3,4,5,6]
B = [13, 21, 34]
A.extend(B)
print(A)

[1, 2, 3, 4, 5, 6, 13, 21, 34]


Question 2

In [33]:
#to create an identity matrix
#first, import the required libraries
import numpy as np
import pandas as pd
x=np.eye(3)

In [7]:
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Question 3

In [8]:
#to import and read in the Hamoye fuel dataset
hamoye_dataset = pd.read_csv('https://raw.githubusercontent.com/WalePhenomenon/climate_change/master/fuel_ferc1.csv')


In [10]:
#to get the first 5 rows of the dataset
hamoye_dataset.head(10)

record_id  utility_id_ferc1  report_year  \
0   f1_fuel_1994_12_1_0_7                 1         1994   
1  f1_fuel_1994_12_1_0_10                 1         1994   
2   f1_fuel_1994_12_2_0_1                 2         1994   
3   f1_fuel_1994_12_2_0_7                 2         1994   
4  f1_fuel_1994_12_2_0_10                 2         1994   
5  f1_fuel_1994_12_2_0_13                 2         1994   
6   f1_fuel_1994_12_2_1_1                 2         1994   
7  f1_fuel_1994_12_2_1_10                 2         1994   
8  f1_fuel_1994_12_2_2_10                 2         1994   
9   f1_fuel_1994_12_4_0_1                 4         1994   

       plant_name_ferc1 fuel_type_code_pudl fuel_unit  fuel_qty_burned  \
0              rockport                coal       ton        5377489.0   
1  rockport total plant                coal       ton       10486945.0   
2                gorgas                coal       ton        2978683.0   
3                 barry                coal       ton        3739484.0   
4             chickasaw                 gas       mcf          40533.0   
5   e. c. gaston-unit 5                coal       ton        2124933.0   
6      joseph m. farley             nuclear       kgU           2260.0   
7   resondent's portion                coal       ton        5372133.0   
8  respondent's portion                coal       ton         817520.0   
9             units 1-3                coal       ton        1471233.0   

   fuel_mmbtu_per_unit  fuel_cost_per_unit_burned  \
0            16.590000                      18.59   
1            16.592000                      18.58   
2            24.130000                      39.72   
3            23.950000                      47.21   
4             1.000000                       2.77   
5            23.922000                      44.24   
6             0.064094                      28.77   
7            24.840000                      58.54   
8            24.290000                      33.97   
9            22.484000                      28.73   

   fuel_cost_per_unit_delivered  fuel_cost_per_mmbtu  
0                         18.53                1.121  
1                         18.53                1.120  
2                         38.12                1.650  
3                         45.99                1.970  
4                          2.77                2.570  
5                         43.25                1.850  
6                          0.00                0.450  
7                         55.13                2.360  
8                         34.65                1.400  
9                         28.11                1.278

In [11]:
#to get the fuel type code  that has the lowest average fuel cost per unit burned
lowest_average_fuel_cost_per_unit_burned = hamoye_dataset.groupby('fuel_type_code_pudl')['fuel_cost_per_unit_burned'].mean().sort_values()
lowest_average_fuel_cost_per_unit_burned

fuel_type_code_pudl
gas          13.659397
other        18.253856
waste        19.518122
coal         67.421830
oil         168.877086
nuclear    4955.157002
Name: fuel_cost_per_unit_burned, dtype: float64

Question 4

In [17]:
#to get the std and 75th percentile of the measure of energy per unit (Fuel_mmbtu_per_unit) in two decimal places.
std_75_percentile = hamoye_dataset['fuel_mmbtu_per_unit'].describe()
std_75_percentile

count    29523.000000
mean         8.492111
std         10.600220
min          0.000001
25%          1.024000
50%          5.762694
75%         17.006000
max        341.260000
Name: fuel_mmbtu_per_unit, dtype: float64

Question 5

In [20]:
#to get the  skewness for the fuel quantity burned 
skewness_of_fuel_quantity_burned = hamoye_dataset['fuel_qty_burned'].skew()
skewness_of_fuel_quantity_burned 

15.851495469109503

In [24]:
#to get the kurtosis for the fuel quantity burned 
kurtosis_fuel_quantity_burned = hamoye_dataset['fuel_qty_burned'].kurtosis()
kurtosis_fuel_quantity_burned 

651.3694501337732

Question 6

In [27]:
#to get the features with missing values
sum_of_null_rows=hamoye_dataset.isnull().sum()
sum_of_null_rows

record_id                         0
utility_id_ferc1                  0
report_year                       0
plant_name_ferc1                  0
fuel_type_code_pudl               0
fuel_unit                       180
fuel_qty_burned                   0
fuel_mmbtu_per_unit               0
fuel_cost_per_unit_burned         0
fuel_cost_per_unit_delivered      0
fuel_cost_per_mmbtu               0
dtype: int64

In [28]:
#to get the percentage of the missing values
per_cent = sum_of_null_rows/100
per_cent

record_id                       0.0
utility_id_ferc1                0.0
report_year                     0.0
plant_name_ferc1                0.0
fuel_type_code_pudl             0.0
fuel_unit                       1.8
fuel_qty_burned                 0.0
fuel_mmbtu_per_unit             0.0
fuel_cost_per_unit_burned       0.0
fuel_cost_per_unit_delivered    0.0
fuel_cost_per_mmbtu             0.0
dtype: float64

Question 7

In [29]:
#to get the category of the feature with the missing value
hamoye_dataset['fuel_unit'].describe()

count     29343
unique        9
top         mcf
freq      11354
Name: fuel_unit, dtype: object

Question 8

In [31]:
#to get the feature with the second and third lowest correlation with the Fuel Cost Per Unit Burned
abs(hamoye_dataset.corr()['fuel_cost_per_unit_burned']).sort_values()

fuel_cost_per_mmbtu             0.000437
fuel_mmbtu_per_unit             0.010034
fuel_cost_per_unit_delivered    0.011007
report_year                     0.013599
fuel_qty_burned                 0.018535
utility_id_ferc1                0.037863
fuel_cost_per_unit_burned       1.000000
Name: fuel_cost_per_unit_burned, dtype: float64

Question 9

In [ ]:
#to get the percentage change in the fuel cost per unit burned in 1998 compared to 1994
fue_type_coal_1994 = hamoye_dataset[(hamoye_dataset['report_year']==1994)& (hamoye_dataset